name: agrigrow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome.png
    - assets/icons/facebook.png
    - assets/icons/google.jpg
    - assets/icons/logo.png
    - assets/images/background_image.png
    - assets/icons/welcome.jpg
    - assets/images/home_2.jpg
    - assets/images/home_3.jpg
    - assets/images/farmer_1.jpg
    - assets/images/farmer_2.jpg
    - assets/images/farmer_3.png
    - assets/images/farmer_4.png
    - assets/images/farmer_5.png


